<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Frames</name>
   <tag></tag>
   <elementGuidId>05cb6619-98e8-4b4b-89ee-98454c04fb33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.subNav > ul.navList > li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c1270306-38a5-4828-8d8b-547e5b94f997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Frames</value>
      <webElementGuid>6e71a662-84c9-486e-a134-14df46a0eb12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[1]/nav[1]/div[@class=&quot;fixedNav&quot;]/div[@class=&quot;subNav&quot;]/ul[@class=&quot;navList&quot;]/li[1]</value>
      <webElementGuid>05d7583d-4529-4ec0-bd38-3d29e35c9640</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::li[1]</value>
      <webElementGuid>69629a55-478c-4814-b226-5c018b88a879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Index'])[1]/following::li[2]</value>
      <webElementGuid>110a68d9-472a-4604-ab61-90e832420e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Frames'])[1]/preceding::li[1]</value>
      <webElementGuid>0fdc01d8-77ff-4c5b-9e72-8a8a1e5c8c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li</value>
      <webElementGuid>d8d90de8-81f4-493d-9208-90f71cf90613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Frames' or . = 'Frames')]</value>
      <webElementGuid>2977457a-eecb-473d-9ad6-2916021bb38a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
