<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_By.Remotable.Parameters</name>
   <tag></tag>
   <elementGuidId>f3405b46-6cb8-4ab1-976f-dfef996fe6e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='i0']/td/code/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.colFirst > code > a[title=&quot;class in org.openqa.selenium&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c6939c05-47b1-4d16-a19c-e641797f6a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>By.Remotable.Parameters.html</value>
      <webElementGuid>1146c4c8-c3bf-4cd4-9f4a-3b186c226c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium</value>
      <webElementGuid>13f53ac7-78a4-4ab4-b738-43d6d830a830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>By.Remotable.Parameters</value>
      <webElementGuid>1a714809-9dde-4930-90c6-2a844469dcef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i0&quot;)/td[@class=&quot;colFirst&quot;]/code[1]/a[1]</value>
      <webElementGuid>63bcdb40-74ff-48f1-a804-c740a53ce120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_By.Remotable/iframe_classFrame</value>
      <webElementGuid>e07d4c58-ac6d-42ec-848f-857a7224c679</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='i0']/td/code/a</value>
      <webElementGuid>1fb8ef52-e48e-41f2-8c96-0c89cd7ba6ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'By.Remotable.Parameters')])[2]</value>
      <webElementGuid>19ac8244-bbd7-4d5f-bb51-cb7d5750a509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[2]/following::a[1]</value>
      <webElementGuid>2daeef80-30cb-4c31-9712-d68d9c1643a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Method'])[3]/following::a[1]</value>
      <webElementGuid>67bf3d4a-72bc-495f-aa8f-009cc13002c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='getRemoteParameters'])[1]/preceding::a[1]</value>
      <webElementGuid>e5a7d5c8-7108-4bec-aa43-e2e5de9259d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'By.Remotable.Parameters.html')])[2]</value>
      <webElementGuid>60fa049f-267e-4a05-93a1-e328cff06034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/code/a</value>
      <webElementGuid>b4983789-e7ae-48de-b30f-45b51f1fa4f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'By.Remotable.Parameters.html' and @title = 'class in org.openqa.selenium' and (text() = 'By.Remotable.Parameters' or . = 'By.Remotable.Parameters')]</value>
      <webElementGuid>bb3756f0-8fde-40f5-a6ba-c97d8a6621e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
